### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by onlyutkarsh**
Fixed a typo in help.

### CODE REVIEW

**Comment by trevorsg** [comment]
Can you resolve the merge conflict? Thanks.

**Comment by onlyutkarsh** [comment]
Sorry Trevor, I see the error `This branch has conflicts that must be resolved` but when I am not getting any option to merge and also file difference is not showing me where is the difference. Can you please assist? Apologies.

**Comment by trevorsg** [comment]
To resolve a merge conflict:
1. Fetch master (git fetch origin master)
2. Merge master to your branch (git merge origin/master)
3. Open the file that contains the merge conflict (in this case, unshare.ts)
4. Remove all diff markers and manually merge the difference. In this case, you need to keep your changes, but change VSO to VSTS.
5. Add the file to the index (git add unshare.ts)
6. Commit the changes (git commit --no-edit)
7. Push to your branch on github.

Once you've done that, the merge button should light up.

**Comment by onlyutkarsh** [comment]
Couldn't get it to work.. Sorry, I am new to git. Anything wrong?

image

**Comment by trevorsg** [comment]
You need to be in your branch (not master) when running those steps.

**Comment by onlyutkarsh** [comment]
I tried that, I was able to do pull request and merge to charisk/tfs-cli repo. I am not sure if that is correct. this is what i did in git bash now. 

image

**Comment by trevorsg** [comment]
Gotta add a remote for Microsoft :)

git checkout TypoFix 
git remote add microsoft https://github.com/Microsoft/tfs-cli.git
git fetch microsoft master
git merge microsoft/master
<fix conflict>
git add unshare.ts
git commit --no-edit
git push origin TypoFix

**Comment by onlyutkarsh** [comment]
Thanks a ton Trevor!! Finally managed to do it.. Thanks for spoon feeding me :-)

**Pull request merged**
